export enum ResponseMessage {
    INVALID_CONFIRM_PASSWORD = 'Confirm password should match with password',
    NOT_EXISTED_USER = 'Invalid user',
    SOMETHING_WRONG = 'Something went wrong',
    EMAIL_TAKEN = 'Email has been taken',
    INVALID_EMAIL_PASSWORD = 'Email or password is not correct',
    EMAIL_NOT_ACTIVE = 'Email is not active',
    INVALID_PHONE = 'Invalid phone number',
    INVALID_GENDER = 'Invalid gender',
    INVALID_PASSWORD = 'Invalid password',
    INVALID_IMAGE = 'Invalid image',
    UNAUTHORIZED = 'Sorry, your request could not be processed',
    NOT_FOUND = 'Page not found',
    DUPLICATED_PASSWORD = 'New password should not be same with current password',
    FORBIDDEN = 'Sorry, your request could not be processed',
    INVALID_CATEGORY = 'Invalid category',
    INVALID_TYPE = 'Invalid type',
    INVALID_SUBJECT = 'Invalid subject',
    INVALID_DESCRIPTION = 'Invalid description',
    INVALID_VIDEO_LINK = 'Invalid video link',
    INVALID_QUIZ = 'Invalid quiz',
    INVALID_DIMENSION = 'Invalid dimension',
    INVALID_LESSON = 'Invalid lesson',
    DUPLICATED_CATEGORY = 'This category has already existed',
}
